### ISSUE TITLE
Add README file with basic setup information

### ISSUE THREAD

**Issue by bcisneros** [EstandaresDeCalidadSW23/vikingos-analyser#1]
## Acceptance Criteria
- Documentation should be easy to read
- Every team member should be able to make a successful setup.

**Comment by DanielDerma** [comment]
Listo profe, esta en #3, listo para mergear, atentos a cualquier indicacion!

**Comment by bcisneros** [comment]
Thanks Daniel. I merged the PR. 
Now the team can start the setup locally. 

@Estrelladelatorre1 please create the required tickets for each team member and assign them respectively.
