### ISSUE TITLE
Luis Hernandez project setup

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#10]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by Estrelladelatorre1** [comment]
Do you have any problems? Just a reminder that the delivery date is today, Tuesday 29-08-2023.

**Comment by luisher25san** [comment]
OK
<img width="960" alt="Captura de pantalla 2023-08-29 171017" src="https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/104661988/1640f324-796b-4238-9240-701c66d41ae1">
