### ISSUE TITLE
Gabriel Project Setup

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#11]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by Estrelladelatorre1** [comment]
Do you have any problems? Just a reminder that the delivery date is today, Tuesday 29-08-2023.

**Comment by wolfgabo** [comment]
![work](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/141535184/a089f13f-1f18-4fcb-b8c6-3b3d3c056208)

**Comment by wolfgabo** [comment]
![imagen](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/141535184/daa2d909-b4cf-464d-b6e8-669eb420f34c)

**Comment by wolfgabo** [comment]
Mission accomplished sister Estrella 💯
