### ISSUE TITLE
SIN EXITO AL CLONAR 

### ISSUE THREAD

**Issue by karibeltran** [EstandaresDeCalidadSW23/vikingos-analyser#12]
"Good afternoon, the folder is created and assigned the folder where the repository will be cloned, then I open Visual Studio and its terminal to enter the codes that come in the README and I get this error."
![Captura de pantalla 2023-08-29 140555](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/102837501/c51ab213-aee4-4e7b-bc76-3cb80ec67bf8)

![Captura de pantalla 2023-08-29 143552](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/102837501/032fe95e-9522-4181-b631-ca227c831a91)

**Comment by bcisneros** [comment]
@karibeltran Please provide more details about the error you are getting and use English.

**Comment by Estrelladelatorre1** [comment]
@karibeltran What is your problem? Attach screenshots

**Comment by bcisneros** [comment]
It looks like you placed the project inside the folder `vikingos`.

Please move to the `vikingos-analyser` folder and run the commands.
