### ISSUE TITLE
Question: top comment in tailwind.config.cjs file

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#14]
What is the purpose of including comments at the top of the file with `/** @type {import('tailwindcss').Config} */`

Does it have any effect on the configuration itself?

**Comment by DanielDerma** [comment]
uses Tailwind CSS and a tool like Visual Studio Code that supports TypeScript or JavaScript type checking.

**Comment by bcisneros** [comment]
@Estrelladelatorre1 please add more context to this question. If @DanielDerma already answered please close the ticket.
