### ISSUE TITLE
Dev: Add placeholder to main text area

### ISSUE THREAD

**Issue by CarlosMoriel** [EstandaresDeCalidadSW23/vikingos-analyser#17]
We need more context to know what is going on, add a placeholder with an example is going to be useful for that:

Actual Result:
![image](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/63763024/c7676796-dbdb-4bb9-af07-7ff332fa9566)

Expected result:
![image](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/63763024/bf214072-1692-439f-b680-d32cae1fab6b)

**Comment by bcisneros** [comment]
@CarlosMoriel maybe this ticket is no longer required with the new requirements. Please check if this can be reused to specify another task or just close it as `won't do`.
