### ISSUE TITLE
docs: add good practices to readme.me

### ISSUE THREAD

**Issue by DanielDerma** [EstandaresDeCalidadSW23/vikingos-analyser#19]
Usar prefijos para tus commits, pr y tickets. para hacerlos más semánticos
use prefix for your commits, pr and tickets, make them more sematics
ie:
```
feat: add new search feature
^--^  ^--------------------^
│     │
│     └--> # Descripción de los cambios
│
└──------> # Tipo del cambio
```

```
feat(backend): add filter for cars
fix(web): remove wrong color
```

**Comment by bcisneros** [comment]
@DanielDerma is this a duplicate of #18? If that is the case please close this ticket or reuse it for another task.

**Comment by bcisneros** [comment]
It is up to the team, but I suggest including the ticket number as a reference

```
feat(moduleXYZ): #123 Adding feature ABC to module XYZ
```
