### ISSUE TITLE
Francisco Project Setup

### ISSUE THREAD

**Issue by bcisneros** [EstandaresDeCalidadSW23/vikingos-analyser#20]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by Estrelladelatorre1** [comment]
@franciscogarcia112200 do you have a problem?

**Comment by franciscogarcia112200** [comment]
![Foto en Git bash](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/143901492/2fabc075-32a5-4046-8cf7-f78f4af9e76c)
![Foto Localhost](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/143901492/dc67a3e3-13b8-4a9c-8df9-1abfad68f57a)
It's ready
Attached evidence

**Comment by bcisneros** [comment]
Thanks Francisco
