### ISSUE TITLE
design: error message with number 0 to 1,000,000

### ISSUE THREAD

**Issue by DanielDerma** [EstandaresDeCalidadSW23/vikingos-analyser#32]
> **Objective**
> 
> For now, the only accepted values for variables are positive numbers from 0 to 1,000,000.
> 
> If any other number or data type is used, the analyzer should throw a Syntactic Error with the following message:
> 
> ```
> Input
> variable numero = -1;
> 
> Output:
> No es válido el número -1.
> ```
> 
> **Acceptance criteria**
> 
> * Demonstrate that a variable can be assigned a positive number from 0-1,000,000.
> * Demonstrate that the application cannot accept negative numbers or other data types.
> 
> Note: The error message should indicate that the number is out of the range.

**Please provide a image edited with the error display**

**Comment by bcisneros** [comment]
@DanielDerma / @luisher25san  I suggest making this ticket more generic to handle all the different errors.

The frontend should only display the errors returned by the analyzer, so make this ticket to provide the UI design.

**Comment by luisher25san** [comment]
[ERRORS EXPLANATION.pdf](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/files/12581518/ERRORS.EXPLANATION.pdf)

Here is my design proposal for the error messages, applied to the situation of a number out of range.

**Comment by DanielDerma** [comment]
just make the design for this ticket, i dont care about another desing for the future
