### ISSUE TITLE
Carlos Project Setup

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#5]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by CarlosMoriel** [comment]
![image](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/63763024/8bcf825d-e4b3-427c-b241-5e4d9164ce7a)

![image](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/63763024/9229cc26-ab8e-4f73-a95e-b8fbe17ffba3)

![image](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/63763024/8361447a-3593-45d8-97a1-52fe9d447496)

**Comment by bcisneros** [comment]
`Syntax Error: Carlos Moriel`

**Comment by Estrelladelatorre1** [comment]
Ok
