### ISSUE TITLE
Daniel Project Setup

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#6]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by DanielDerma** [comment]
![image](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/37880797/cdae6018-7d01-4850-8b17-52196e068681)

**Comment by Estrelladelatorre1** [comment]
Ok
