### ISSUE TITLE
Hugo Project Setup

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#7]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by Estrelladelatorre1** [comment]
Do you have any problems? Just a reminder that the delivery date is today, Tuesday 29-08-2023.

**Comment by Hugo-Hdez** [comment]
Hi, Estrella. Thank you for your preoccupation and thanks for offering your help =)
Attached the evidence in screenshots:

1. npm install and npm run dev

npm install:
![mintty_GsWKypcUqi](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/82738193/d11dcb11-4ee2-4ee6-a513-5cbfe9fc9070)

npm run dev:
![mintty_npdSBusikD](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/82738193/d839c3d9-ea55-42a7-8be0-3b5688c2aa43)

2. i open http://localhost:5173/
![58EHiN8DZv](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/82738193/4dd45f99-8d67-4839-a280-6a0c987a59cc)

Thanks for your time, have a good week!
