### ISSUE TITLE
Jair Project Setup

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#8]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by Estrelladelatorre1** [comment]
Do you have any problems? Just a reminder that the delivery date is today, Tuesday 29-08-2023.

**Comment by JairMendez43** [comment]
Work done !

![Captura de pantalla 2023-08-29 211406](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/134170235/45abd7dc-f5f2-402c-968a-ebfc0b93e0ba)
