### ISSUE TITLE
Karina Project Setup

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#9]
## Acceptance Criteria
- Project must be able to run in local
- Attach evidence to this ticket (screenshot)
- Report any issue to Daniel/Carlos/Estrella creating a new ticket with the details

**Comment by Estrelladelatorre1** [comment]
Do you have any problems? Just a reminder that the delivery date is today, Tuesday 29-08-2023.

**Comment by karibeltran** [comment]
![Captura de pantalla 2023-08-29 151213](https://github.com/EstandaresDeCalidadSW23/vikingos-analyser/assets/102837501/85bb65da-4822-49da-87bf-96c8548e26eb)

**Comment by Estrelladelatorre1** [comment]
Ok
